development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: truetoronto_development
  pool: 5
  username: filipetorqueto
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: truetoronto_test
  pool: 5
  username: filipe
  password:

production:
  adapter: postgresql
  host: pgsql.truetoronto.com.br
  encoding: unicode
  database: truetoronto
  pool: 5
  username: truetoronto
  password: Samy107456